# permissions for end users to view markdownviews.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: markdownview-viewer-role
rules:
- apiGroups:
  - view.k8s.alicey.dev
  resources:
  - markdownviews
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - view.k8s.alicey.dev
  resources:
  - markdownviews/status
  verbs:
  - get
